#%RAML 1.0
title: Sample API
version: v1
baseUri: http://localhost:8081/api

/api/v1/users:
  get:
    description: Get all users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "users": []
              }
  post:
    description: Create a new user
    body:
      application/json:
        example: |
          {
            "name": "John Doe"
          }
    responses:
      201:
        body:
          application/json

/api/v1/orders:
  get:
    description: Get all orders
    responses:
      200:
        body:
          application/json
  post:
    description: Create a new order
    responses:
      201:
        body:
          application/json

/api/v1/data:
  get:
    description: Get data
    responses:
      200:
        body:
          application/json

